config/routes.rb
Rails.application.routes.draw do
  resources :supernodes

  resources :nodes do
    resources :stats
  end

  match 'nodes/:node_id/stats/:type/:name' => 'stats#show', via: :get

  root 'nodes#index'

end

app/models/collectd_stat.rb
class CollectdStat
	attr_accessor :base_dir
	def name
		self.base_dir.split('/').last
	end

	def data_files
		Dir["#{base_dir}/*"].map do |file|
			File.new(file)
		end
	end
end

app/models/node.rb
class Node
	
	@@base_dir = Rails.configuration.database_configuration[Rails.env]["rrd_path"]
	@@default_ping_target = Rails.configuration.database_configuration[Rails.env]["rtt_target"]
	attr_accessor :id
	attr_accessor :name
	def self.all
		nodes = []
		Dir.entries(@@base_dir).each do |entry|
			# Ist das ein Node?
			if md = entry.match('^([a-fA-F0-9]{12})')
				n = Node.new
				n.id = md[0].to_i(16)
				n.name = entry
				nodes << n
			end
		end
		nodes.sort { |x,y| x.id <=> y.id }
	end

	def path
		id_str = id.to_s(16)
		Dir["#{@@base_dir}/#{id_str}*"][0]
	end

	def self.find(id)
		n = Node.new
		n.id = id
		dir_str = n.path
		n.name = dir_str[@@base_dir.size,dir_str.size].gsub('/','')
		n
	end

	def last_submitted_timestamp
		File.mtime(Dir["#{path}/**/*.rrd"].max_by {|f| File.mtime(f)})
	end	

	def collectd_stats
		Dir["#{path}/*"].map do |path|
			c = CollectdStat.new
			c.base_dir = path
			c
		end
	end

	def node_id 
		self.id.to_s(16)
	end

	def rtt_5_min
		begin
			self.stat_template("ping",@@default_ping_target).rtt_5_min
		rescue Exception => e
			Rails.logger.error "Unable to calcuate rtt_5_min #{e}"		
			Float::NAN
		end
	end

	def loss_5_min
		begin
			self.stat_template("ping",@@default_ping_target).loss_5_min
		rescue Exception => e
			Rails.logger.error "Unable to calcuate loss_5_min #{e}"		
			Float::NAN
		end
	end

	@@plugins = {"ping" => Collectd::Stats::PingStat,
		"interface" => Collectd::Stats::InterfaceRxTxStat,
		"iwinfo" => Collectd::Stats::IwinfoStat}
	def stat_template(plugin_str,rrd_str)
		# Sanity: Check if plugin exists
		plugin = @@plugins[plugin_str]
		raise "Plugin #{plugin_str} unknown " if plugin.nil?
		
		#Create template with rrd-File to render
		plugin.new("#{path}/#{plugin_str}/#{rrd_str}")
	end

end

app/models/supernode.rb
class Supernode < Node

	@@base_dir = Rails.configuration.database_configuration[Rails.env]["rrd_path"]
	
	attr_accessor :name
	
	def self.all
		nodes = []
		Dir.entries(@@base_dir).each do |entry|
			# Ist das ein Node?
			if md = entry.match('^fastd(\d\d?).kbu.freifunk.net')
				n = Node.new
				n.name = entry
				nodes << n
			end
		end
		nodes.sort { |x,y| x.id <=> y.id }
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_headers

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Expose-Headers'] = 'ETag'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
    headers['Access-Control-Max-Age'] = '86400'
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
    respond_to do |format|
      format.html # index.html.erb
      format.json do 
        data = {}
        @nodes.each do |n|
          loss_5_min = n.loss_5_min
          rtt_5_min = n.rtt_5_min 
          data[n.id] = {id_hex: n.node_id, 
            loss_5_min: (loss_5_min.nil? || loss_5_min.nan?) ? 1.0 : loss_5_min, 
            rtt_5_min: (rtt_5_min.nil? || rtt_5_min.nan?) ? nil : rtt_5_min}
        end
        render json: data
      end
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      id = params[:id].to_i
      @node = Node.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
 
  def show
    @node = Node.find(params[:node_id].to_i)
    # Sanity check - does the rrd-file (target) exist for this host?
    stat = @node.stat_template(params[:id],params[:target])
    secs = (params[:secs] || 3600).to_i
    name = params[:name]
    type = params[:type]
    id = params[:id] || params[:type]
    width = params[:width] || 600
    height = params[:height] || 200
    no_summary = params[:no_summary]
    respond_to do |format|
      format.png do 
        send_data stat.create_graph(width,height,secs,no_summary), :type => 'image/png',:disposition => 'inline'
      end
    end
  end
end

app/controllers/supernodes_controller.rb
class SupernodesController < ApplicationController
  before_action :set_supernode, only: [:show, :edit, :update, :destroy]

  # GET /supernodes
  # GET /supernodes.json
  def index
    @supernodes = Supernode.all
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
	def ping?(stat)
		stat.name.match("ping")
	end
	
	def interface?(stat)
		stat.name.match("interface")
	end
	
	def iwinfo?(stat)
		stat.name.match("iwinfo")
	end

	def ping_img(node,target)
		"<img />"
	end
	#Hack: Bei iwinfo wird der Plugin-Name um das Interface ergaenzt :-/
	def iwinfo_dir(path)
		path.split('/')[-2..-1].join '/'
	end

	def active?(node)
		# Sind Daten in der letzten Minute empfangen worden?
		now = Time.new
		(now - node.last_submitted_timestamp) < 60
	end
end

app/helpers/supernodes_helper.rb
module SupernodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cserv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="https://github.com/yanosz/cserv">CServ - Collectd Service</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Nodes", nodes_path %></li>
        <li><a href="#about">About</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for @node, :html => { :class => "form-horizontal node" } do |f| %>

    <% if @node.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @node.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@node[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            nodes_path, :class => 'btn btn-default' %>

<% end %>

app/views/nodes/edit.html.erb
<%- model_class = Node -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nodes/index.html.erb
<div class="page-header">
  <h1>Nodes</h1>
</div>
Folgende Nodes haben Statistiken übermittelt.<p />
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>ID (dezimal)</th>
      <th>Hostname</th>
      <th>Aktiv</th>
      <th>RTT 5 min</th>
      <th>Loss 5 min</th>
      <th>Letzter Datensatz übermittelt</th>
    </tr>
  </thead>
  <tbody>
    <% row = 0 %>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= row+=1  %></td>
        <td><%= link_to "#{node.id}".rjust(15,'0'), node_path(node.id) %></td>
        <td><%= link_to node.name, node_path(node.id) %></td>
        <td> 
          <% if active?(node) %>
            <span class="label label-success">Ja</span>
          <% else %>
            <span class="label label-danger">Nein</span>
          <% end %> 
        <td><%= node.rtt_5_min.round 2 %></td>
        <td><%= node.loss_5_min.round 2 %></td>
          
        <td><%= node.last_submitted_timestamp %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/nodes/new.html.erb
<%- model_class = Node -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nodes/show.html.erb
<div class="page-header">
  <h1>Statistiken zu Node <%= @node.node_id %></h1>
</div>

<% @node.collectd_stats.each do |stat| %>
<div class="page-header">
	<h2><%= stat.name %></h2>
</div>

<div class="row">
  <div class="col-md-6">
		<table class="table table-striped">
			<thead>
				<tr>
		  			<th>Name</th>
		  			<th>Größe</th>
		  			<th>Letzte Änderung</th>
				</tr>
			</thead>
			<tbody>
				<% stat.data_files.each do |f| %>
			    <tr>
					    <td><%= File.basename(f.path)  %></td>
					    <td><%= f.size / 1024  %> KB</td>
					    <td><%= f.mtime  %></td>
			    </tr>
			    <% end %>
		  </tbody>
		</table>
  </div>
  <div class="col-md-1">
  	<!-- Eine Graphik RTT / Loss fuer jeden Ping-Host -->
	<% if ping?(stat) %>
		<% stat.data_files.each do |f| %>
			<!-- Droprate, STDEV verwerfen, Dateien haben die Form ping-fdd3:5d16:b5dd:3::6.rrd -->
			<% if md = File.basename(f.path).match('^ping-(.+).rrd') %>
				<img src ="<%= node_stat_path(@node.id,'ping')%>.png?secs=86400&width=600&height=200&target=<%= File.basename(f.path) %>" />
			<% end %>
		<% end %>
	<% end %>  	


  	<!-- Eine Graphik RX/TX fuer jedes Interface -->
	<% if interface?(stat) %>
		<% stat.data_files.each do |f| %>
			<!-- Droprate, STDEV verwerfen, Dateien haben die Form ping-fdd3:5d16:b5dd:3::6.rrd -->
			<% if md = File.basename(f.path).match('^if_octets-(.+).rrd') %>
				<img src ="<%= node_stat_path(@node.id,'interface')%>.png?secs=86400&width=600&height=200&target=<%= File.basename(f.path) %>" />
			<% end %>
		<% end %>
	<% end %>  	

  	<!-- Eine Graphik (Stations) fuer jedes wlan-Interface -->
	<% if iwinfo?(stat) %>
		<% stat.data_files.each do |f| %>
			<!-- Droprate, STDEV verwerfen, Dateien haben die Form ping-fdd3:5d16:b5dd:3::6.rrd -->
			<% if md = File.basename(f.path).match('stations.rrd') %>
				<img src ="<%= node_stat_path(@node.id,'iwinfo')%>.png?secs=86400&width=600&height=200&target=<%= iwinfo_dir(f.path) %>" />
			<% end %>
		<% end %>
	<% end %>  	


  </div>
</div>

	
<% end %>

app/views/supernodes/_form.html.erb
<%= form_for(@supernode) do |f| %>
  <% if @supernode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supernode.errors.count, "error") %> prohibited this supernode from being saved:</h2>

      <ul>
      <% @supernode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supernodes/edit.html.erb
<h1>Editing supernode</h1>

<%= render 'form' %>

<%= link_to 'Show', @supernode %> |
<%= link_to 'Back', supernodes_path %>

app/views/supernodes/index.html.erb
<h1>Listing supernodes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supernodes.each do |supernode| %>
      <tr>
        <td><%= link_to 'Show', supernode %></td>
        <td><%= link_to 'Edit', edit_supernode_path(supernode) %></td>
        <td><%= link_to 'Destroy', supernode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supernode', new_supernode_path %>

app/views/supernodes/new.html.erb
<h1>New supernode</h1>

<%= render 'form' %>

<%= link_to 'Back', supernodes_path %>

app/views/supernodes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_supernode_path(@supernode) %> |
<%= link_to 'Back', supernodes_path %>